import { INBOX_SESSION_ID } from '@lobechat/const';

/**
 * Fork-only PWA manifest members that make the installed web app behave like a
 * native one: it appears in the OS share sheet, and its launcher icon carries
 * long-press shortcuts.
 *
 * Kept out of `manifest.ts` (an upstream file) so upstream rebases only ever
 * touch the single spread that pulls these in.
 */

/** Landing route for anything the OS hands us — the default inbox conversation. */
const INBOX_ROUTE = `/agent/${INBOX_SESSION_ID}`;

/**
 * Query param carrying the shared text. `SharedTextFromUrl` reads it and drops
 * the payload into the composer instead of sending it, so the user can edit or
 * add context before the message goes out.
 */
export const SHARE_TEXT_PARAM = 'share_text';
export const SHARE_TITLE_PARAM = 'share_title';
export const SHARE_URL_PARAM = 'share_url';

/**
 * Web Share Target. Deliberately `GET`: a `POST` target is only delivered to a
 * service-worker `fetch` handler, which would put the whole share flow behind
 * SW registration and lifecycle. `GET` arrives as ordinary query params that
 * the SPA router can read on first paint.
 *
 * Files are intentionally not accepted — that requires `POST` + `enctype`.
 */
export const shareTarget = {
  action: INBOX_ROUTE,
  method: 'GET',
  params: {
    text: SHARE_TEXT_PARAM,
    title: SHARE_TITLE_PARAM,
    url: SHARE_URL_PARAM,
  },
} as const;

/**
 * Launcher shortcuts (long-press the icon on Android, right-click in a desktop
 * dock). Names stay in English: this manifest is generated by a Next.js route
 * that has no locale in scope, and the sibling `name` / `description` fields
 * are English for the same reason.
 *
 * Keep the list short — Android surfaces at most 4 and drops the rest silently.
 */
export const shortcuts = [
  {
    name: 'New Chat',
    short_name: 'Chat',
    url: INBOX_ROUTE,
  },
  {
    name: 'Image Generation',
    short_name: 'Image',
    url: '/image',
  },
  {
    name: 'Tasks',
    short_name: 'Tasks',
    url: '/tasks',
  },
] as const;
